"""sub history

Revision ID: 200e699eb1eb
Revises: 4c30de01dd04
Create Date: 2025-06-11 19:17:45.568950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200e699eb1eb'
down_revision: Union[str, None] = '4c30de01dd04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('subscription_type', sa.String(), nullable=True))
    # ### end Alembic commands ###
    op.execute("""
    CREATE TABLE subscription_history (
        history_id SERIAL PRIMARY KEY,
        subscription_id INT REFERENCES subscription(subscription_id),
        wallet_id INT REFERENCES wallet(wallet_id),
        plan_id INT REFERENCES plan(plan_id),
        status TEXT,
        action_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        comment TEXT
    );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'subscription_type')
    op.execute("DROP TABLE IF EXISTS subscription_history;")
    # ### end Alembic commands ###
