"""changes

Revision ID: 4c30de01dd04
Revises: a132916898f6
Create Date: 2025-06-10 15:41:03.388921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c30de01dd04'
down_revision: Union[str, None] = 'a132916898f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_transaction', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('partner_transaction_parnter_id_fkey'), 'partner_transaction', type_='foreignkey')
    op.create_foreign_key(None, 'partner_transaction', 'partner', ['partner_id'], ['partner_id'])
    op.drop_column('partner_transaction', 'parnter_id')
    op.add_column('plan', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('plan', 'token')
    op.drop_column('wallet', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallet', sa.Column('token', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('plan', sa.Column('token', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('plan', 'price')
    op.add_column('partner_transaction', sa.Column('parnter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'partner_transaction', type_='foreignkey')
    op.create_foreign_key(op.f('partner_transaction_parnter_id_fkey'), 'partner_transaction', 'partner', ['parnter_id'], ['partner_id'])
    op.drop_column('partner_transaction', 'partner_id')
    # ### end Alembic commands ###
