"""fourth schema

Revision ID: 8ca19c2a2135
Revises: bfab1f48eac8
Create Date: 2025-06-05 13:12:59.088358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca19c2a2135'
down_revision: Union[str, None] = 'bfab1f48eac8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('token', sa.Float(), nullable=True))
    op.drop_column('plan', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('plan', 'token')
    # ### end Alembic commands ###
