"""third schema

Revision ID: bfab1f48eac8
Revises: d45c43d71551
Create Date: 2025-06-05 12:46:46.042984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfab1f48eac8'
down_revision: Union[str, None] = 'd45c43d71551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner', sa.Column('commission_rate', sa.Float(), nullable=True))
    op.add_column('partner', sa.Column('commission_type', sa.String(), nullable=True))
    op.drop_column('partner_transaction', 'commission_rate')
    op.drop_column('partner_transaction', 'commission_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('partner_transaction', sa.Column('commission_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('partner_transaction', sa.Column('commission_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('partner', 'commission_type')
    op.drop_column('partner', 'commission_rate')
    # ### end Alembic commands ###
